// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/accreditation.tsx";
import * as $5 from "./routes/akvaplanist.tsx";
import * as $6 from "./routes/article/[slug].tsx";
import * as $7 from "./routes/dcat.tsx";
import * as $8 from "./routes/doi.tsx";
import * as $9 from "./routes/home.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/mynewsdesk-articles/[slug].tsx";
import * as $12 from "./routes/nav.tsx";
import * as $13 from "./routes/news.tsx";
import * as $14 from "./routes/null.tsx";
import * as $15 from "./routes/pref.tsx";
import * as $16 from "./routes/pubs.tsx";
import * as $17 from "./routes/research.tsx";
import * as $18 from "./routes/research_topics.tsx";
import * as $19 from "./routes/search.tsx";
import * as $20 from "./routes/service_topics.tsx";
import * as $21 from "./routes/services.tsx";
import * as $22 from "./routes/topics.tsx";
import * as $$0 from "./islands/HScrollWithDynamicImage.tsx";
import * as $$1 from "./islands/button_open_dialog.tsx";
import * as $$2 from "./islands/doi_search.tsx";
import * as $$3 from "./islands/lang_switcher.tsx";
import * as $$4 from "./islands/pubs_histogram.tsx";
import * as $$5 from "./islands/text.tsx";
import * as $$6 from "./islands/theme_switcher.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/accreditation.tsx": $4,
    "./routes/akvaplanist.tsx": $5,
    "./routes/article/[slug].tsx": $6,
    "./routes/dcat.tsx": $7,
    "./routes/doi.tsx": $8,
    "./routes/home.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/mynewsdesk-articles/[slug].tsx": $11,
    "./routes/nav.tsx": $12,
    "./routes/news.tsx": $13,
    "./routes/null.tsx": $14,
    "./routes/pref.tsx": $15,
    "./routes/pubs.tsx": $16,
    "./routes/research.tsx": $17,
    "./routes/research_topics.tsx": $18,
    "./routes/search.tsx": $19,
    "./routes/service_topics.tsx": $20,
    "./routes/services.tsx": $21,
    "./routes/topics.tsx": $22,
  },
  islands: {
    "./islands/HScrollWithDynamicImage.tsx": $$0,
    "./islands/button_open_dialog.tsx": $$1,
    "./islands/doi_search.tsx": $$2,
    "./islands/lang_switcher.tsx": $$3,
    "./islands/pubs_histogram.tsx": $$4,
    "./islands/text.tsx": $$5,
    "./islands/theme_switcher.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
